spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:mysql://localhost:3306/customer_master
    driver: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: false
